sudo: false
language: java
jdk:
- openjdk8
- openjdk11
addons:
  apt:
    packages:
    - graphviz
script: "./gradlew stage"
env:
  global:
    secure: GYlh3uBAVCELaufhp68tRv/XZCbBST29ypa/52QDzuDnyj8HQ2mXTGguyNvYtdLBLMbN+BEW7MwuBa4NpGgD16LuWx4AN+ZBdN9JyY/DV3I7PlpdloOkKAnoEBhoRUQPeX3QjLdlG7QMWWxeEj/7spvrvbLHOcIH845olCe9XT2t9Nrpzo/p6j7UG4E8Y81HQDRpcCbSux/2SmYD63xuS9sqdyfpKeVx/lIYmT0CdBKM6ewjZ1w+3v9kmq1nVa08wCF76oCcJrDnlPXAqMSDtb4sNn525brXw+TuxlGIxuzRGEmtTX6muuUZZ+1gPhrFuduH7Z1x8AUkB8H/hcD/7x9XxWjaDJh923NFRuTNNUb5V0BWMFodfwvGrZeNBJc1PyuDLKzi9L3r3RBrRwCX2WYnf36Gsyg0ia13jQFVymYBlsgXE1glNzkuue7+lg/v7M4GoQtKp9PvKrV/tjNBidXbZfjTGUYMpSqw2yyJsIeC2Y3AjeQwDePiW19dnQEpFFJWandaur0OsQz8ViQeLho5E79TCy/G68o4n6ghca2JMjqYyAdSpyombaIJB8OvBdIgqFjFiy975CpiFdxXwm0a2UY9M8ioJrlrUYOrQbu9bwOYYo1Q4l93weDwiR4vICCzQW/84DeMqC7EyjJHRfbR6tCc+1A8JXyDzOKaCCw=
